export const DetailsData = [
    {
        Welcome:"Smile Integreted Global Services is An Indigenous custom Clearing and Freight Forwarding service. About Smile Integreted Global Services, We are a Nigerian based custom clearing and Freight Forwarding company based in Lagos, Nigeria. With our Track record, we pride ourselves as one of the RELIABLE CLEARING SERVICE COMPANY that delivers a prompt and professional services to our clients We are known for our quality assured import and export Freight Forwarding services and Transportation; Sea, Air, Rail and Road",
        Services:"At Smile Integreted Global Services, we strive to provide our customers with fastest and reliable services, which regularly exceed their expectations. Our systems and procedures support us in our aim of gaining a deep expertise in our customers’ industries and achieving total customer satisfaction. We provide the best Custom Clearance services in Lagos ports and port Harcourt.",
        ImportClearance:"Smile Integreted Global Services is one of the leading Customs Clearing Agents that smoothly handles customs clearing of import consignments across international ports.",
        ImportAndExport:"Are you looking to expand your business beyond borders? Look no further! Our export experts specializes in connecting you to lucrative international markets, opening up a world of opportunities for your products or services.📞 Contact Us Today to Start Your Export Journey! 📞",
        LogisticsConsultation:"The Logistics Consultants can assist you in deciding which processes or functions should be outsourced and can also assist you in selecting a suitable service provider.",
        Wharehousing: "The Logistics Consultants can assist whether you are looking to implement a new facility, expand an existing site, or maximize your assets.",
    }
]